export const roomCopy = {
  it: {
    missionTitle: "Missione: Ripristina l’energia",
    missionText:
      "Il laboratorio è in blocco e il sistema di sicurezza è attivo.\nSblocca tutte le serrature risolvendo gli enigmi, prima che scada il tempo.",
    startMissionLabel: "Inizia missione",
    rulesTimeLabel: "Tempo a disposizione",
    rulesHintLabel: "Indizi",
    rulesUnlockLabel: "Enigmi",
    rulesUnlockSuffix: "serrature da sbloccare",
    rulesGoalLabel: "Obiettivo",
    rulesGoalText: "sblocca tutte le serrature e riaccendi il laboratorio",
    hudTimeLabel: "Tempo",
    hudEnergyLabel: "Energia",
    hudKeysLabel: "Chiavi",
    hintLabel: "Indizio",
    lockedLabel: "Enigma bloccato",
    completedLabel: "Sbloccato ✓",
    completionTitle: "Complimenti!",
    completionSubtitle: "Hai completato l'escape room e riattivato il laboratorio.",
    completionTimeLabel: "Tempo",
    completionPrintLabel: "Esporta PDF",
    completionNewGameLabel: "Nuova partita",
    completionInfoLabel: "Hint usati",
    completionScoreLabel: "Punteggio",
    missionFallbackLine: "Sblocca tutte le serrature risolvendo gli enigmi.",
  },
  en: {
    missionTitle: "Mission: Restore Power",
    missionText:
      "The lab is locked down and the safety system is active.\nUnlock every lock by solving the puzzles before time runs out.",
    startMissionLabel: "Start Mission",
    rulesTimeLabel: "Time available",
    rulesHintLabel: "Hints",
    rulesUnlockLabel: "Puzzles",
    rulesUnlockSuffix: "locks to open",
    rulesGoalLabel: "Goal",
    rulesGoalText: "unlock all locks and restore power",
    hudTimeLabel: "Time",
    hudEnergyLabel: "Energy",
    hudKeysLabel: "Keys",
    hintLabel: "Hint",
    lockedLabel: "Locked puzzle",
    completedLabel: "Unlocked ✓",
    completionTitle: "Well done!",
    completionSubtitle: "You restored the lab and completed the escape room.",
    completionTimeLabel: "Time",
    completionPrintLabel: "Print PDF",
    completionNewGameLabel: "New game",
    completionInfoLabel: "Hints used",
    completionScoreLabel: "Score",
    missionFallbackLine: "Unlock every lock by solving the puzzles.",
  },
} as const;
